Description: >
  This Cloudformation template creates an Amazon EMR Cluster

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: 'Hudi'

  EEKeyPair:
    Description: SSH key (for access to EMR instances)
    Type: AWS::EC2::KeyPair::KeyName
    Default: ee-default-keypair


Resources:

  EMRSparkHudiCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Sub ${EnvironmentName} Spark EMR Cluster
      JobFlowRole: EMR_EC2_DefaultRole
      ReleaseLabel: emr-6.5.0
      ScaleDownBehavior: TERMINATE_AT_TASK_COMPLETION
      LogUri: !Join [ '', [ 's3://aws-logs-', !Ref 'AWS::AccountId', '-', !Ref 'AWS::Region', '/elasticmapreduce/' ]]
      ServiceRole: EMR_DefaultRole
      Tags:
        - Key: 'Name'
          Value: !Sub ${EnvironmentName} Spark EMR Cluster
      VisibleToAllUsers: true
      Applications:
        - Name: Spark
        - Name: Hive
        - Name: Hadoop
      Configurations:
        #- Classification: presto-connector-hive
        #  ConfigurationProperties:
        #     "hive.metastore.glue.datacatalog.enabled": "true"
        #- Classification: spark
        #  ConfigurationProperties:
        #    "maximizeResourceAllocation": "true"
        #- Classification: spark-defaults
        #  ConfigurationProperties:
        #    "spark.driver.extraClassPath": "/home/hadoop/javalib/*:/usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*:/usr/share/aws/hmclient/lib/aws-glue-datacatalog-spark-client.jar:/usr/share/java/Hive-JSON-Serde/hive-openx-serde.jar:/usr/share/aws/sagemaker-spark-sdk/lib/sagemaker-spark-sdk.jar"
        - Classification: hive-site
          ConfigurationProperties:
             "hive.metastore.client.factory.class": "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"
        - Classification: spark-hive-site
          ConfigurationProperties:
             "hive.metastore.client.factory.class": "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"
      EbsRootVolumeSize: 32
      #BootstrapActions:
      #  - Name: setup-delta-lake
      #    ScriptBootstrapAction:
      #      Path: s3://aksh-test-versioning/delta/delta-init.sh
      Instances:
        AdditionalMasterSecurityGroups: [ !ImportValue WorkshopSecurityGroup ]
        AdditionalSlaveSecurityGroups: [ !ImportValue WorkshopSecurityGroup ]
        Ec2KeyName: !Ref EEKeyPair
        Ec2SubnetId: !ImportValue PublicSubnet1
        MasterInstanceGroup:
          EbsConfiguration:
            EbsBlockDeviceConfigs:
              - VolumeSpecification:
                  SizeInGB: 100
                  VolumeType: gp2
          InstanceCount: 1
          InstanceType: r5.2xlarge
          Market: ON_DEMAND
          Name: 'Master instance group'
        #CoreInstanceGroup:
        #  EbsConfiguration:
        #    EbsBlockDeviceConfigs:
        #      - VolumeSpecification:
        #          SizeInGB: 100
        #          VolumeType: gp2
        #  InstanceCount: 2
        #  InstanceType: r4.2xlarge
        #  Market: ON_DEMAND
        #  Name: 'Core instance group'

Outputs:

  EmrSparkClusterId:
    Value: !Ref EMRSparkHudiCluster

